language: java
jdk:
- openjdk8
script:
- "./gradlew check"
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
    secure: "e2f52e88-969b-48e4-9158-8b8eff6c98e7"
    app: javatoes